### ISSUE TITLE
Unable to annotate class consts with a type, leading to error in strict mode

### ISSUE THREAD

**Issue by Kilenaitor** [hhvm/hack-codegen#105]
`CodegenClassish`'s `addConst` and `buildConsts` just simply export the const in the format of `const <name> = <value>`.

In strict mode, this triggers a Hack 2035 error requesting a type annotation be provided. Unfortunately, there's no way to provide one. 

Solution would be to probably do what the other `add*Const` functions do and request a `$type` variable and modify the `addWithSuggestedLineBreaksf` pattern to `const <type> <name> = <value>`.

**Comment by fredemmott** [comment]
You currently need to put the 'type' in the 'name' field - #72 for fixing this.
