### ISSUE TITLE
CodegenEnum should stop extending CodegenClassish

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-codegen#106]
CodegenClassish has too many features, such as abstract constants, interfaces, type constants, parent classes.

**Comment by gmarcotte** [comment]
I think this change makes it so that there's no way to add an enum into a CodegenFile, since there are only methods to addClass (CodegenClassish, which no longer works for enums), addConstant, addTrait, addFunction, and add(Before/After)Types.  Unless I'm missing something.
