### ISSUE TITLE
Fix fixmes for variadics

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hack-codegen#25]
```
/* HH_FIXME[4033] variadic params with type constraints are not supported */
```

Given that 3.12 support has been dropoped, these can all be cleaned up

**Comment by simonwelsh** [comment]
`hh_client --remove-dead-fixmes` will do this for you

**Comment by fredemmott** [comment]
TIL, thanks - though still lots of manual work because:

 - ` Was expecting a type hint (what about: array) (Typing[4033])`
 - ` . Invalid return type (Typing[4110])`

**Comment by fredemmott** [comment]
:/ This didn't actually find them all, weird.
