### ISSUE TITLE
Support short-array syntax for arrays

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hack-codegen#67]
`HackBuilderValues::valueArray` and `::keyValueArray` both generate `array(...)`. Would be nice if it could use `[...]` instead.

**Comment by fredemmott** [comment]
Do you have a particular need for this? I'm against it as:
 - it would be an additional obstacle for re-unifying with Facebook's internal version
 - we're advocating moving to vec/dict/keyset anyway, so this should matter less in the future
 - it doesn't seem to gain much

**Comment by simonwelsh** [comment]
Mostly stylistic reasons. Sounds like it won't be worth it.
