### ISSUE TITLE
CodegenFile doesn't have useClass

### ISSUE THREAD

**Issue by simonwelsh** [hhvm/hack-codegen#70]
Mentioned in https://hhvm.github.io/hack-codegen/docs/classes/CodegenFile/

Rather than removing the reference to it, the method should be added instead as it's a rather important thing to be able to do.

**Comment by simonwelsh** [comment]
@fredemmott would still be good to have a `useClass` method

**Comment by fredemmott** [comment]
Would you want this to do something different to ‘useType’, or just be an alias?

**Comment by simonwelsh** [comment]
`useType` adds in `use type blah`, rather than the `use blah` needed for a class

**Comment by fredemmott** [comment]
‘use type foo’ works for classes, type aliases etc

‘use foo’ is equivalent to ‘use namespace foo; use type foo;’ unless there’s a conflicting use statement

**Comment by fredemmott** [comment]
This didn't hit a release, but originally it was going to be `use class Foo`; we went for `use type` instead as they share a symbol table, and go through the same autoloader path - e.g. this would be meaningless:

```
<?hh
use type Foo\Bar;
use class Baz\Bar;

function foo(Bar $baz);
```
